
export const setoresEconomicos = [
  "Agronegócio",
  "Alimentação e Bebidas",
  "Automotivo",
  "Aviação",
  "Banco e Finanças",
  "Biotecnologia",
  "Comunicação e Marketing",
  "Construção Civil",
  "Consultoria",
  "Cosmética e Beleza",
  "E-commerce",
  "Educação",
  "Energia",
  "Entretenimento",
  "Farmacêutico",
  "Imobiliário",
  "Indústria Química",
  "Logística e Transporte",
  "Moda e Têxtil",
  "Petróleo e Gás",
  "Saúde",
  "Segurança",
  "Serviços Financeiros",
  "Tecnologia da Informação",
  "Telecomunicações",
  "Turismo e Hotelaria",
  "Varejo",
  "Mecânica Automotiva",
  "Agência de Viagens",
  "Serviços Jurídicos"
];
