// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndssmckwmtthkionhkik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kc3NtY2t3bXR0aGtpb25oa2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDA4NTksImV4cCI6MjA2NTg3Njg1OX0.HgoaMK8DxnNXsgBa8cWOA7W0FkVBeMxW0T-hTk77aL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);